# invoke the resolve goal a second time after package, to force the plugin to read from the cache
# (a second `package` would re-run maven-jar-plugin, which no longer permits replacing the main artifact)
invoker.goals = clean package org.exist-db.maven.plugins:public-xar-repo-plugin:resolve@fetch-xars
